### ISSUE TITLE
判定活动签到返回空数组的问题

### ISSUE THREAD

**Issue by WinHGGG** [Tao0Lu/Arknights_Checkin#4]
In LINE 311: if ($j->user->activity->CHECKIN_ONLY) 应为 if (count((array)$j->user->activity->CHECKIN_ONLY))

**Comment by WinHGGG** [comment]
In LINE  748: if ($res=='error') 应为 if ($res !=='error')

**Comment by WinHGGG** [comment]
In LINE 769: 应先判定items是否为空 if(count((array)$j->items)==0)return;

**Comment by Tao0Lu** [comment]
fixed
